# Generated by Django 4.2.25 on 2025-11-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkFile',
        ),
    ]
